web_api: 'http://localhost:5005/api/v1/track?'
web_api_frequency: 10
web_api_verify_connection: false
web_api_open_browser: true
indicators:
  - class_name: Scalar
    is_print: false
    name: param.*
    options:
      comet: false
  - class_name: Scalar
    is_print: false
    name: grad.*
    options:
      comet: false
  - class_name: Scalar
    is_print: false
    name: module.*
    options:
      comet: false
  - class_name: Scalar
    is_print: false
    name: optim.*
    options:
      comet: false

